In [2]:
import numpy as np

# 1차원 배열 생성
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [3]:
import numpy as np

# 2차원 배열 생성
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np

# 0으로 채워진 배열 생성
arr3 = np.zeros(5)
print(arr3)

[0. 0. 0. 0. 0.]


In [5]:
import numpy as np

# 1로 채워진 배열 생성
arr4 = np.ones((2, 3))
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
import numpy as np

# 랜덤한 값으로 채워진 배열 생성
arr5 = np.random.rand(2, 3)
print(arr5)

[[0.58225006 0.79060741 0.74825582]
 [0.74131572 0.26558025 0.00201074]]


In [7]:
import numpy as np

# 배열 연산
arr6 = np.array([1, 2, 3])
arr7 = np.array([4, 5, 6])
arr8 = arr6 + arr7
print(arr8)


[5 7 9]


In [8]:
import numpy as np

# 배열 슬라이싱
arr9 = np.array([1, 2, 3, 4, 5])
arr10 = arr9[2:4]
print(arr10)

[3 4]


In [9]:
import numpy as np

# 배열 인덱싱
arr11 = np.array([1, 2, 3, 4, 5])
arr12 = arr11[[0, 3]]
print(arr12)


[1 4]


In [11]:
import numpy as np

# 배열 형태 바꾸기
arr13 = np.array([[1, 2], [3, 4], [5, 6]])
arr14 = arr13.reshape(2, 3)
print(arr14)


[[1 2 3]
 [4 5 6]]


In [12]:
import numpy as np

# 배열 정렬하기
arr15 = np.array([3, 1, 4, 2, 5])
arr16 = np.sort(arr15)
print(arr16)


[1 2 3 4 5]


In [13]:
import numpy as np

# 배열 연산 함수 사용
arr17 = np.array([1, 2, 3])
arr18 = np.array([4, 5, 6])
arr19 = np.add(arr17, arr18)
print(arr19)


[5 7 9]


In [14]:
import numpy as np

# 배열 복사하기
arr20 = np.array([1, 2, 3])
arr21 = arr20.copy()
print(arr21)


[1 2 3]


In [15]:
import numpy as np

# 배열 차원 추가하기
arr22 = np.array([1, 2, 3])
arr23 = np.expand_dims(arr22, axis=1)
print(arr23)


[[1]
 [2]
 [3]]


In [16]:
import numpy as np

# 배열 요소 지우기
arr24 = np.array([1, 2, 3, 4, 5])
arr25 = np.delete(arr24, 2)
print(arr25)


[1 2 4 5]


In [17]:
import numpy as np

# 배열 요소 검색하기
arr28 = np.array([1, 2, 3, 4, 5])
arr29 = np.where(arr28 == 3)
print(arr29)


(array([2], dtype=int64),)


In [18]:
import numpy as np

# 배열 요소 중복 제거하기
arr30 = np.array([1, 2, 3, 1, 2, 3, 4, 5])
arr31 = np.unique(arr30)
print(arr31)


[1 2 3 4 5]


In [24]:
import numpy as np

# 배열 연산 축 지정하기
arr32 = np.array([[1, 2, 3], [4, 5, 6]])
arr33 = np.sum(arr32, axis=0)
print(arr33)


[ 6 15]


In [22]:
import numpy as np

# 배열 병합하기
arr34 = np.array([1, 2, 3])
arr35 = np.array([4, 5, 6])
arr36 = np.concatenate((arr34, arr35))
print(arr36)


[1 2 3 4 5 6]


In [23]:
import numpy as np

# 배열 인덱스 정렬하기
arr37 = np.array([3, 1, 4, 2, 5])
arr38 = np.argsort(arr37)
print(arr38)


[1 3 0 2 4]
